sources:
  - name: source
    database: "{{ 'gcp-dbt-project-503007' if target.type == 'bigquery' else target.catalog }}"
    schema: "{{ 'dbt_sales' if target.type == 'bigquery' else 'source' }}"
    tables:
      - name: fact_sales
      - name: fact_returns
      - name: dim_date
      - name: dim_store
      - name: dim_product
      - name: dim_customer
      - name: items