dbt_project_apoorva:
  outputs:
    dev:
      catalog: dbt_project
      host: dbc-a920f698-7997.cloud.databricks.com
      http_path: /sql/1.0/warehouses/d21e700deeacaec8
      schema: default
      threads: 1
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      type: databricks
    prod:
      catalog: dbt_project_prod
      host: dbc-a920f698-7997.cloud.databricks.com
      http_path: /sql/1.0/warehouses/d21e700deeacaec8
      schema: default
      threads: 1
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      type: databricks
    bigquery:
      type: bigquery
      method: service-account
      project: gcp-dbt-project-503007
      dataset: dbt_sales
      location: asia-south1
      threads: 4
      keyfile: C:\Users\APOORVA KULKARNI\.gcp\dbt-runner-key.json
  target: bigquery